# Makefile automatically generated by ghdl
# Version: GHDL 0.35-dev (tarball) [Dunoon edition] - GCC back-end code generator
# Command used to generate this makefile:
# ghdl --gen-makefile --ieee=synopsys vga_tb
SRCS := vram.vhd\
	vga_tb.vhd\
	vga.vhd\
	vga_controller.vhd\
	vga_pic_gen.vhd\
	pic_gen.vhd
OBJS := $(SRCS:vhd=o)

GHDL=ghdl
GHDLFLAGS= --ieee=synopsys
GHDLRUNFLAGS= --wave=wave.ghw

# Default target
all: vga_tb

# Elaboration target
vga_tb: $(OBJS)
	$(GHDL) -e $(GHDLFLAGS) $@

clean:
	rm $(OBJS) vga_tb
# Run target
run: vga_tb
	$(GHDL) -r vga_tb $(GHDLRUNFLAGS)

# Targets to analyze files
%.o: %.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
