set_property PACKAGE_PIN Y21  [get_ports b_0]
set_property PACKAGE_PIN Y20  [get_ports b_1]
set_property PACKAGE_PIN AB22 [get_ports g_0]
set_property PACKAGE_PIN AA22 [get_ports g_1]
set_property PACKAGE_PIN AB21 [get_ports g_2]
set_property PACKAGE_PIN AA19 [get_ports h_sync]
set_property PACKAGE_PIN V20  [get_ports r_0]
set_property PACKAGE_PIN U20  [get_ports r_1]
set_property PACKAGE_PIN V19  [get_ports r_2]
set_property PACKAGE_PIN Y19  [get_ports v_sync]
set_property IOSTANDARD LVCMOS33 [get_ports b_0]
set_property IOSTANDARD LVCMOS33 [get_ports b_1]
set_property IOSTANDARD LVCMOS33 [get_ports g_0]
set_property IOSTANDARD LVCMOS33 [get_ports g_1]
set_property IOSTANDARD LVCMOS33 [get_ports g_2]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports r_0]
set_property IOSTANDARD LVCMOS33 [get_ports r_1]
set_property IOSTANDARD LVCMOS33 [get_ports r_2]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]

#set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 33]]